### ISSUE TITLE
Feature Request: Send Raw Command(s)

### ISSUE THREAD

**Issue by rakalex** [crowbarz/ha-pioneer_async#79]
It would be nice if we can send a raw commands which is not implemented in integration.

<img width="1582" alt="Image" src="https://github.com/user-attachments/assets/4b726499-30d7-47e5-910a-d216fc7909d2" />

**Comment by crowbarz** [comment]
I guess I'd prefer to be supporting any arbitrary command through a named command, rather than using the raw command.

Any particular reason that you're trying to change the input manually instead of using `media_player.select_source`?

**Comment by crowbarz** [comment]
Also you should be able to achieve what you are trying to do with `FN` in that image by entering `select_source` as the command, enabling the `Prefix` option, and entering `44` in that option's text field. The list of commands is in the source, you should be able to find the friendly name of the raw command by searching for the raw command.

Note though that I'm considering how to deprecate `prefix` and `suffix` as commands that take arguments are able to type and bounds check the command's argument(s) on the aiopioneer side, though I haven't worked out how that will work on the HA side yet.

**Comment by crowbarz** [comment]
Looks like you are trying to send some network commands (`nnNW`) to the AVR that aren't currently available.

Once crowbarz/aiopioneer#68 is included in the next `aiopioneer` and HA integration release, then you will be able to send the following new commands via `send_command` in a script in HA. It will use the existing connection to the AVR, rather than creating a new connection like your script currently does. You might need to insert `delay` actions to emulate the sleep commands in your script.

```
    "operation_network_play": {Zone.Z1: ["10NW", "NW"]},
    "operation_network_pause": {Zone.Z1: ["11NW", "NW"]},
    "operation_network_previous": {Zone.Z1: ["12NW", "NW"]},
    "operation_network_next": {Zone.Z1: ["13NW", "NW"]},
    "operation_network_rewind": {Zone.Z1: ["14NW", "NW"]},
    "operation_network_fastforward": {Zone.Z1: ["15NW", "NW"]},
    "operation_network_display": {Zone.Z1: ["18NW", "NW"]},
    "operation_network_stop": {Zone.Z1: ["20NW", "NW"]},
    "operation_network_up": {Zone.Z1: ["26NW", "NW"]},
    "operation_network_down": {Zone.Z1: ["27NW", "NW"]},
    "operation_network_right": {Zone.Z1: ["28NW", "NW"]},
    "operation_network_left": {Zone.Z1: ["29NW", "NW"]},
    "operation_network_enter": {Zone.Z1: ["30NW", "NW"]},
    "operation_network_return": {Zone.Z1: ["31NW", "NW"]},
    "operation_network_program": {Zone.Z1: ["32NW", "NW"]},
    "operation_network_clear": {Zone.Z1: ["33NW", "NW"]},
    "operation_network_repeat": {Zone.Z1: ["34NW", "NW"]},
    "operation_network_random": {Zone.Z1: ["35NW", "NW"]},
    "operation_network_menu": {Zone.Z1: ["36NW", "NW"]},
    "operation_network_edit": {Zone.Z1: ["37NW", "NW"]},
    "operation_network_class": {Zone.Z1: ["38NW", "NW"]},
```

**Comment by rakalex** [comment]
<img width="1239" alt="Image" src="https://github.com/user-attachments/assets/5abe5154-992e-4f91-860e-9a31ea33b4fc" /> 

Not sure that I understand how to use it. Can you explain me?

**Comment by pantherale0** [comment]
@rakalex try using the command name instead, the library should do the mapping for you. For example:

```
action: pioneer_async.send_command
data:
  entity_id: media_player.living_room_avr
  command: operation_network_next
```

**Comment by rakalex** [comment]
<img width="1245" alt="Image" src="https://github.com/user-attachments/assets/32a52fb1-a676-4048-a911-4ece7aa6ba32" />

swill not working

**Comment by crowbarz** [comment]
You'll first need to upgrade to `pioneer_async` 0.12.0 as those commands were added in that release.

**Comment by rakalex** [comment]
<img width="289" alt="Image" src="https://github.com/user-attachments/assets/19bd7a32-d12e-4901-99eb-3d5bb27ca0c0" />

I did it already

**Comment by crowbarz** [comment]
Try `network_next` - the commands were renamed in `aiopioneer`. This is mentioned in that package's release notes, but I will add them to the `pioneer_async` release notes as well

**Comment by rakalex** [comment]
Yes, it's working now. Thank you, for your work!

**Comment by rakalex** [comment]
Ok, another issue. So it's working fine now, I triggered the action, it switched to next track. Then after couple of seconds I got next error message. 

<img width="730" alt="Image" src="https://github.com/user-attachments/assets/40514585-26ca-4ac7-83fe-481107a2ef27" />

**Comment by rakalex** [comment]
<img width="1258" alt="Image" src="https://github.com/user-attachments/assets/8c0089c5-d848-4f91-a466-43210fd904a3" />

More errors for investigate the issue. It's working, sometime doesn't. 

As far as I understand, there is a built in retry logic or something should be. So what I want to say, it's a strange issue, since there is no any other connections made to receiver. 

I will rewrite my original DLNA script to use yours, and see how it's working, I will do testing for couple days.

**Comment by crowbarz** [comment]
Only commands that set a specific state (eg. power on or volume level set) will automatically retry on timeout, because sending the same command two or more times has the same effect as sending it once (ie. it is idempotent). Multiple `network_next` commands move the cursor once for each command, so these commands don't retry.

Your bash script had `sleep` commands in it to delay the second and subsequent commands. Did you include equivalent delays in your HA script? For some commands, especially on-screen display commands, the default delay between consecutive AVR commands isn't long enough.

**Comment by crowbarz** [comment]
You might also want to set the script mode to `queued` so the script doesn't run multiple times in parallel, and also add a delay at the end of the script so there is a delay between queued script runs.

**Comment by rakalex** [comment]
I did some testing, found few my automations have stopped working. Not sure, but I couldn't roll back to previous version.

<img width="986" alt="Image" src="https://github.com/user-attachments/assets/57106132-3211-443a-baa2-d49ebc999897" />

**Comment by rakalex** [comment]
<img width="964" alt="Image" src="https://github.com/user-attachments/assets/5c9b7f46-1c5e-4866-872e-90c45467d874" />

<img width="934" alt="Image" src="https://github.com/user-attachments/assets/aa8c9751-1b70-4fae-8ee3-54941b3c9a6b" />

Do you need some steps to reproduce the issue?

**Comment by crowbarz** [comment]
You would need to document the state of your AVR at the time that these commands were run, or enable integration debug logging from when the zone is powered off to when your script is run to capture the current state.

All I can tell from what you have sent is that the AVR returned an error when you tried to run these commands (when it says `command currently unavailable`) or didn't respond at all. It could be as simple as the AVR zone was not powered on, when most commands are not available, or, in the case of `network_next`, a source that does not support network commands was selected at the time. I can't tell anything more from just a list of the errors returned by the AVR.

If you want your script to be more robust, then it needs to first change the AVR to the correct state before sending the commands, something like this (note: this snippet is unverified):

```
- if: "{{ not is_state('media_player.pioneer_avr_main_zone', 'on') }}"
  then:
    # turn on AVR main zone
    - action: media_player.turn_on
      target:
        entity_id: media_player.pioneer_avr_main_zone
- if: "{{ not is_state_attr('media_player.pioneer_avr_main_zone', 'source', 'Spotify') }}"
  then:
    # change main zone source to Spotify
    - action: media_player.select_source
      target:
        entity_id: media_player.pioneer_avr_main_zone
      data:
        source: Spotify
```

Otherwise, your script would be the equivalent of just blindly pressing buttons on the remote without consideration for the current AVR state.

**Comment by rakalex** [comment]
`actions:
  - type: turn_on
    device_id: ba4807b2541665b3bd1c2b695d49a315
    entity_id: switch.smart_plug_pioneer_1
    domain: switch
  - wait_for_trigger:
      - entity_id:
          - media_player.pioneer_avr
        to: "off"
        trigger: state
    continue_on_timeout: false
    timeout:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - data: {}
    target:
      entity_id: media_player.pioneer_avr
    action: media_player.turn_on
  - delay:
      hours: 0
      minutes: 0
      seconds: 2
      milliseconds: 500
  - if:
      - condition: time
        before: "08:00:00"
        after: "05:00:00"
    then:
      - data:
          volume_level: 0.09
        target:
          entity_id: media_player.pioneer_avr
        action: media_player.volume_set
    else:
      - data:
          volume_level: 0.29
        target:
          entity_id: media_player.pioneer_avr
        action: media_player.volume_set
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
  - data:
      source: INTERNET RADIO
    target:
      entity_id: media_player.pioneer_avr
    action: media_player.select_source
mode: single`

This script was created like 1 year ago. It was working fine. Since the last version 0.12 it stopped working as many other automations as well. Every time I change the volume - I got error. Every time I execute action "network_next" I got error. Usually I get error, when the action is done, meaning volume is changed but then got error message, same for other actions, like next track. I can record a video or something else. But it's strange that you're not experiencing the same issue as me. I believe avr same model year. Maybe some settings on integration? I'm talking not about initial bash script, I'm talking about any actions integration fails.

**Comment by rakalex** [comment]
<img width="719" alt="Image" src="https://github.com/user-attachments/assets/4551e2d8-cacf-479b-ac39-23e59e748332" />

https://github.com/user-attachments/assets/56c95e99-1277-4919-b8ae-d10204206194

AVR is ON, the command actually executed and changed the volume, but as you can see on video it throw error.

**Comment by crowbarz** [comment]
Let me try to replicate it on my VSX-930 with your script. I have automations that change the volume, but I  normally use a Harmony hub to turn the AVR on via IR and waits until Harmony finishes.

An immediate thought is that the `set_volume` command is conflicting with the full refresh of the AVR that the HA integration performs when the main zone is powered on the first time after a reconnect. As of 0.12, the full refresh now runs in the command queue thread. I need to check if other commands are blocked while the full refresh is running. I am pretty sure it was in previous versions.

If you run the script when the smart plug is already on and the AVR main zone has been turned on at least once (so the full refresh has already been run), does it still throw errors?

I realise it is not optimal, but you may also be able to work around the issue by increasing the delay after the AVR is turned on. My own scripts wait 10s after the AVR reconnects for the full refresh to finish.

**Comment by rakalex** [comment]
Man, forget about script and smart plug and power state. The device is turned ON for couple hours and changed volume, changed track - many times (also with errors as described below), then I just try to run any command:

1) it gives me an error up front - no actions are made, then second attempt will work.
2) it gives me an error as on video, the action is executed, but then I get error.


It was working fine with 0.11. Never had an issue with volume.

**Comment by crowbarz** [comment]
I am trying to second guess the issue as I have insufficient information. The screen recording doesn't help understanding the issue, and I can't replicate the behaviour you describe on my AVR.

The integration debug log will be needed to troubleshoot this issue any further.

**Comment by rakalex** [comment]
`attempting initial refresh for Main Zone
2025-05-30 07:59:54.640 DEBUG (MainThread) [aiopioneer.connection] sending command: ?P
2025-05-30 07:59:54.649 ERROR (MainThread) [homeassistant.components.automation.pioneer_turn_on_by_chair] Pioneer Turn On in the morning: If at step 5: Error executing script. Error for call_service at pos 1: Entity media_player.pioneer_avr does not support action media_player.volume_set
2025-05-30 07:59:54.650 ERROR (MainThread) [homeassistant.components.automation.pioneer_turn_on_by_chair] Pioneer Turn On in the morning: Error executing script. Error for if at pos 5: Entity media_player.pioneer_avr does not support action media_player.volume_set
2025-05-30 07:59:54.659 ERROR (MainThread) [homeassistant.components.automation.pioneer_turn_on_by_chair] Error while executing automation automation.pioneer_turn_on_by_chair: Entity media_player.pioneer_avr does not support action media_player.volume_set`

`2025-05-30 08:03:24.551 DEBUG (MainThread) [custom_components.pioneer_async.coordinator] Manually updated pioneer_async data
2025-05-30 08:03:27.206 DEBUG (MainThread) [aiopioneer.pioneer_avr] send_command raised exception: AVR command 13NW timed out
2025-05-30 08:03:27.207 ERROR (MainThread) [homeassistant.components.script.next_station] Next Station: Choose at step 1: choice 3: Error executing script. Error for call_service at pos 2: AVR command network_next returned error: AVR command 13NW timed out
2025-05-30 08:03:27.207 ERROR (MainThread) [homeassistant.components.script.next_station] Next Station: Error executing script. Error for choose at pos 1: AVR command network_next returned error: AVR command 13NW timed out
2025-05-30 08:03:27.210 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139715418590224] AVR command network_next returned error: AVR command 13NW timed out`

**Comment by rakalex** [comment]
here, I changed to next track, it switched to next, but few seconds later throw an error message


2025-05-30 08:05:19.100 DEBUG (MainThread) [aiopioneer.decode] undecoded response: RGK0
2025-05-30 08:05:19.181 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GBH08
2025-05-30 08:05:19.182 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GCH0201010""
2025-05-30 08:05:19.183 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GDH000010000100001
2025-05-30 08:05:19.184 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH01020"Back To Me"
2025-05-30 08:05:19.185 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH02023"1:55"
2025-05-30 08:05:19.186 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH03021"Krakota"
2025-05-30 08:05:19.186 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH04022"Back To Me"
2025-05-30 08:05:19.187 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH05024""
2025-05-30 08:05:19.189 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH06026"mp3"
2025-05-30 08:05:19.189 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH07027"320000"
2025-05-30 08:05:19.190 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH08031"0"
2025-05-30 08:05:19.199 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GHH01
2025-05-30 08:05:19.339 DEBUG (MainThread) [aiopioneer.decode] undecoded response: RGK0
2025-05-30 08:05:19.345 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GBH08
2025-05-30 08:05:19.346 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GCH0201010""
2025-05-30 08:05:19.348 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GDH000010000100001
2025-05-30 08:05:19.367 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH01020"Back To Me"
2025-05-30 08:05:19.368 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH02023"1:55"
2025-05-30 08:05:19.371 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH03021"Krakota"
2025-05-30 08:05:19.371 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH04022"Back To Me"
2025-05-30 08:05:19.371 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH05024""
2025-05-30 08:05:19.375 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH06026"mp3"
2025-05-30 08:05:19.376 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH07027"320000"
2025-05-30 08:05:19.377 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH08031"0"
2025-05-30 08:05:19.377 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GHH01
2025-05-30 08:05:19.389 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GBH08
2025-05-30 08:05:19.394 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GCH0201010""
2025-05-30 08:05:19.395 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GDH000010000100001
2025-05-30 08:05:19.396 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH01020"Back To Me"
2025-05-30 08:05:19.399 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH02023"1:55"
2025-05-30 08:05:19.400 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH03021"Krakota"
2025-05-30 08:05:19.402 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH04022"Back To Me"
2025-05-30 08:05:19.402 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH05024""
2025-05-30 08:05:19.408 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH06026"mp3"
2025-05-30 08:05:19.408 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH07027"320000"
2025-05-30 08:05:19.417 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH08031"0"
2025-05-30 08:05:19.432 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GHH01
2025-05-30 08:05:20.594 DEBUG (MainThread) [aiopioneer.connection] sending command: ?S
2025-05-30 08:05:20.624 DEBUG (MainThread) [custom_components.pioneer_async.coordinator] Manually updated pioneer_async data
2025-05-30 08:05:20.697 DEBUG (MainThread) [aiopioneer.connection] sending command: ?AST
2025-05-30 08:05:20.742 DEBUG (MainThread) [aiopioneer.decode] response callback: check_input_multichannel -> []
2025-05-30 08:05:20.742 DEBUG (MainThread) [custom_components.pioneer_async.coordinator] Manually updated pioneer_async data
2025-05-30 08:05:20.798 DEBUG (MainThread) [aiopioneer.connection] sending command: ?VST
2025-05-30 08:05:20.854 DEBUG (MainThread) [custom_components.pioneer_async.coordinator] Manually updated pioneer_async data
2025-05-30 08:05:20.856 DEBUG (MainThread) [aiopioneer.command_queue] >> command queue completed
2025-05-30 08:05:23.663 WARNING (MainThread) [homeassistant.helpers.script] Error in 'choose[0]' evaluation: In 'state':
  In 'state' condition: unknown entity media_player.vsx_1123_airplay
2025-05-30 08:05:23.664 WARNING (MainThread) [homeassistant.helpers.script] Error in 'choose[0]' evaluation: In 'state':
  In 'state' condition: unknown entity media_player.vlc_telnet_2
2025-05-30 08:05:23.666 DEBUG (MainThread) [custom_components.pioneer_async.media_player] >> send_command(1, command=network_next, prefix=None, suffix=None, args=[])
2025-05-30 08:05:23.671 DEBUG (MainThread) [aiopioneer.connection] sending command: 13NW
2025-05-30 08:05:23.707 DEBUG (MainThread) [aiopioneer.decode] undecoded response: NXA
2025-05-30 08:05:24.197 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GIC000""
2025-05-30 08:05:24.757 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GBH08
2025-05-30 08:05:24.806 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GCH0601010""
2025-05-30 08:05:24.813 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GDH000010000100001
2025-05-30 08:05:24.894 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH01020""
2025-05-30 08:05:25.046 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH02023"0:00"
2025-05-30 08:05:25.080 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH03021""
2025-05-30 08:05:25.765 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH04022""
2025-05-30 08:05:25.765 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH05024""
2025-05-30 08:05:25.766 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH06026""
2025-05-30 08:05:25.766 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH07027""
2025-05-30 08:05:25.767 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH08031"0"
2025-05-30 08:05:25.767 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GHH01
2025-05-30 08:05:25.767 INFO (MainThread) [aiopioneer.decode] Global: amp.display: 'Back To Me' -> 'No Title' ('024E6F205469746C65202020202020')
2025-05-30 08:05:25.767 DEBUG (MainThread) [custom_components.pioneer_async.coordinator] Manually updated pioneer_async data
2025-05-30 08:05:25.770 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GIC048"http://192.168.88.65:8200/AlbumArt/1181-3260.jpg"
2025-05-30 08:05:25.805 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GBH08
2025-05-30 08:05:25.807 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GCH0201010""
2025-05-30 08:05:25.808 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GDH000010000100001
2025-05-30 08:05:25.821 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH01020"Burning In My Soul"
2025-05-30 08:05:25.823 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH02023"0:00"
2025-05-30 08:05:25.824 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH03021"Robby East"
2025-05-30 08:05:25.826 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH04022"Burning In My Soul"
2025-05-30 08:05:25.827 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH05024""
2025-05-30 08:05:25.827 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH06026"mp3"
2025-05-30 08:05:25.831 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH07027"320000"
2025-05-30 08:05:25.832 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH08031"0"
2025-05-30 08:05:25.832 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GHH01
2025-05-30 08:05:25.856 INFO (MainThread) [aiopioneer.decode] Global: amp.display: 'No Title' -> 'Burning In My' ('024275726E696E6720496E204D7920')
2025-05-30 08:05:25.857 DEBUG (MainThread) [custom_components.pioneer_async.coordinator] Manually updated pioneer_async data
2025-05-30 08:05:25.960 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GBH08
2025-05-30 08:05:25.964 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GCH0201010""
2025-05-30 08:05:25.978 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GDH000010000100001
2025-05-30 08:05:25.981 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH01020"Burning In My Soul"
2025-05-30 08:05:25.983 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH02023"0:01"
2025-05-30 08:05:25.986 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH03021"Robby East"
2025-05-30 08:05:25.987 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH04022"Burning In My Soul"
2025-05-30 08:05:25.989 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH05024""
2025-05-30 08:05:25.989 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH06026"mp3"
2025-05-30 08:05:25.990 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH07027"320000"
2025-05-30 08:05:25.994 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH08031"0"
2025-05-30 08:05:25.994 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GHH01
2025-05-30 08:05:27.696 INFO (MainThread) [aiopioneer.decode] Global: amp.display: 'Burning In My' -> 'urning In My S' ('0275726E696E6720496E204D792053')
2025-05-30 08:05:27.697 DEBUG (MainThread) [custom_components.pioneer_async.coordinator] Manually updated pioneer_async data
2025-05-30 08:05:28.185 INFO (MainThread) [aiopioneer.decode] Global: amp.display: 'urning In My S' -> 'rning In My So' ('02726E696E6720496E204D7920536F')
2025-05-30 08:05:28.186 DEBUG (MainThread) [custom_components.pioneer_async.coordinator] Manually updated pioneer_async data
2025-05-30 08:05:28.674 DEBUG (MainThread) [aiopioneer.pioneer_avr] send_command raised exception: AVR command 13NW timed out
2025-05-30 08:05:28.675 ERROR (MainThread) [homeassistant.components.script.next_station] Next Station: Choose at step 1: choice 3: Error executing script. Error for call_service at pos 2: AVR command network_next returned error: AVR command 13NW timed out
2025-05-30 08:05:28.676 ERROR (MainThread) [homeassistant.components.script.next_station] Next Station: Error executing script. Error for choose at pos 1: AVR command network_next returned error: AVR command 13NW timed out
2025-05-30 08:05:28.684 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139715418590224] AVR command network_next returned error: AVR command 13NW timed out
2025-05-30 08:05:28.688 INFO (MainThread) [aiopioneer.decode] Global: amp.display: 'rning In My So' -> 'ning In My Sou' ('026E696E6720496E204D7920536F75')
2025-05-30 08:05:28.688 DEBUG (MainThread) [custom_components.pioneer_async.coordinator] Manually updated pioneer_async data
2025-05-30 08:05:29.211 INFO (MainThread) [aiopioneer.decode] Global: amp.display: 'ning In My Sou' -> 'ing In My Soul' ('02696E6720496E204D7920536F756C')
2025-05-30 08:05:29.212 DEBUG (MainThread) [custom_components.pioneer_async.coordinator] Manually updated pioneer_async data
2025-05-30 08:05:29.699 INFO (MainThread) [aiopioneer.decode] Global: amp.display: 'ing In My Soul' -> 'ng In My Soul' ('026E6720496E204D7920536F756C20')
2025-05-30 08:05:29.700 DEBUG (MainThread) [custom_components.pioneer_async.coordinator] Manually updated pioneer_async data
2025-05-30 08:05:30.195 INFO (MainThread) [aiopioneer.decode] Global: amp.display: 'ng In My Soul' -> 'g In My Soul' ('026720496E204D7920536F756C2020')
2025-05-30 08:05:30.195 DEBUG (MainThread) [custom_components.pioneer_async.coordinator] Manually updated pioneer_async data
2025-05-30 08:05:30.697 INFO (MainThread) [aiopioneer.decode] Global: amp.display: 'g In My Soul' -> 'In My Soul' ('0220496E204D7920536F756C202020')
2025-05-30 08:05:30.698 DEBUG (MainThread) [custom_components.pioneer_async.coordinator] Manually updated pioneer_async data
2025-05-30 08:05:31.201 DEBUG (MainThread) [custom_components.pioneer_async.coordinator] Manually updated pioneer_async data
2025-05-30 08:05:31.708 INFO (MainThread) [aiopioneer.decode] Global: amp.display: 'In My Soul' -> 'n My Soul' ('026E204D7920536F756C2020202020')
2025-05-30 08:05:31.709 DEBUG (MainThread) [custom_components.pioneer_async.coordinator] Manually updated pioneer_async data
2025-05-30 08:05:32.230 INFO (MainThread) [aiopioneer.decode] Global: amp.display: 'n My Soul' -> 'My Soul' ('02204D7920536F756C202020202020')
2025-05-30 08:05:32.230 DEBUG (MainThread) [custom_components.pioneer_async.coordinator] Manually updated pioneer_async data
2025-05-30 08:05:32.722 DEBUG (MainThread) [custom_components.pioneer_async.coordinator] Manually updated pioneer_async data











`2025-05-30 08:08:24.199 DEBUG (MainThread) [custom_components.pioneer_async.coordinator] Manually updated pioneer_async data
2025-05-30 08:08:24.614 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GIC048"http://192.168.88.65:8200/AlbumArt/1042-2855.jpg"
2025-05-30 08:08:24.855 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GBH08
2025-05-30 08:08:24.858 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GCH0201010""
2025-05-30 08:08:24.859 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GDH000010000100001
2025-05-30 08:08:24.861 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH01020"Baltimore"
2025-05-30 08:08:24.862 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH02023"0:00"
2025-05-30 08:08:24.862 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH03021"Nina Simone"
2025-05-30 08:08:24.863 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH04022"Baltimore"
2025-05-30 08:08:24.868 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH05024""
2025-05-30 08:08:24.868 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH06026"mp3"
2025-05-30 08:08:24.869 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH07027"320000"
2025-05-30 08:08:24.873 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH08031"0"
2025-05-30 08:08:24.874 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GHH01
2025-05-30 08:08:24.887 INFO (MainThread) [aiopioneer.decode] Global: amp.display: 'Burning In My' -> 'No Title' ('024E6F205469746C65202020202020')
2025-05-30 08:08:24.887 DEBUG (MainThread) [custom_components.pioneer_async.coordinator] Manually updated pioneer_async data
2025-05-30 08:08:25.112 INFO (MainThread) [aiopioneer.decode] Global: amp.display: 'No Title' -> 'Baltimore' ('0242616C74696D6F72652020202020')
2025-05-30 08:08:25.112 DEBUG (MainThread) [custom_components.pioneer_async.coordinator] Manually updated pioneer_async data
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   150  100   150    0     0   2317      0 --:--:-- --:--:-- --:--:--  2343
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   150  100   150    0     0   2275      0 --:--:-- --:--:-- --:--:--  2307
2025-05-30 08:09:42.382 WARNING (MainThread) [homeassistant.helpers.script] Error in 'choose[0]' evaluation: In 'state':
  In 'state' condition: unknown entity media_player.vsx_1123_airplay
2025-05-30 08:09:42.383 WARNING (MainThread) [homeassistant.helpers.script] Error in 'choose[0]' evaluation: In 'state':
  In 'state' condition: unknown entity media_player.vlc_telnet_2
2025-05-30 08:09:42.384 DEBUG (MainThread) [custom_components.pioneer_async.media_player] >> send_command(1, command=network_next, prefix=None, suffix=None, args=[])
2025-05-30 08:09:42.384 DEBUG (MainThread) [aiopioneer.connection] sending command: 13NW
2025-05-30 08:09:42.413 DEBUG (MainThread) [aiopioneer.decode] undecoded response: NXA
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   150  100   150    0     0   2379      0 --:--:-- --:--:-- --:--:--  2419
2025-05-30 08:09:42.934 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GIC000""
2025-05-30 08:09:43.215 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GBH08
2025-05-30 08:09:44.167 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GCH0601010""
2025-05-30 08:09:44.167 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GDH000010000100001
2025-05-30 08:09:44.167 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH01020"Baltimore"
2025-05-30 08:09:44.167 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH02023"0:00"
2025-05-30 08:09:44.168 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH03021"Nina Simone"
2025-05-30 08:09:44.168 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH04022"Baltimore"
2025-05-30 08:09:44.168 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH05024""
2025-05-30 08:09:44.170 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH06026"mp3"
2025-05-30 08:09:44.170 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH07027"320000"
2025-05-30 08:09:44.170 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH08031"0"
2025-05-30 08:09:44.170 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GHH01
2025-05-30 08:09:44.296 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GIC047"http://192.168.88.65:8200/AlbumArt/847-2293.jpg"
2025-05-30 08:09:44.519 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GBH08
2025-05-30 08:09:44.535 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GCH0201010""
2025-05-30 08:09:44.536 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GDH000010000100001
2025-05-30 08:09:44.537 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH01020""
2025-05-30 08:09:44.538 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH02023"0:00"
2025-05-30 08:09:44.539 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH03021""
2025-05-30 08:09:44.540 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH04022""
2025-05-30 08:09:44.541 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH05024""
2025-05-30 08:09:44.541 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH06026"mp3"
2025-05-30 08:09:44.543 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH07027"320000"
2025-05-30 08:09:44.543 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH08031"0"
2025-05-30 08:09:44.544 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GHH01
2025-05-30 08:09:44.559 INFO (MainThread) [aiopioneer.decode] Global: amp.display: 'Baltimore' -> 'No Title' ('024E6F205469746C65202020202020')
2025-05-30 08:09:44.559 DEBUG (MainThread) [custom_components.pioneer_async.coordinator] Manually updated pioneer_async data
2025-05-30 08:09:44.589 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GBH08
2025-05-30 08:09:44.591 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GCH0201010""
2025-05-30 08:09:44.593 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GDH000010000100001
2025-05-30 08:09:44.594 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH01020"Open Your Eyes"
2025-05-30 08:09:44.595 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH02023"0:00"
2025-05-30 08:09:44.600 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH03021"Lansdowne"
2025-05-30 08:09:44.612 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH04022"Blue Collar Revolver"
2025-05-30 08:09:44.613 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH05024""
2025-05-30 08:09:44.614 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH06026"mp3"
2025-05-30 08:09:44.615 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH07027"320000"
2025-05-30 08:09:44.616 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GEH08031"0"
2025-05-30 08:09:44.627 DEBUG (MainThread) [aiopioneer.decode] undecoded response: GHH01
2025-05-30 08:09:44.835 INFO (MainThread) [aiopioneer.decode] Global: amp.display: 'No Title' -> 'Open Your Eyes' ('024F70656E20596F75722045796573')
2025-05-30 08:09:44.835 DEBUG (MainThread) [custom_components.pioneer_async.coordinator] Manually updated pioneer_async data
2025-05-30 08:09:47.011 WARNING (MainThread) [homeassistant.components.script.next_station] Next Station: Already running
2025-05-30 08:09:47.386 DEBUG (MainThread) [aiopioneer.pioneer_avr] send_command raised exception: AVR command 13NW timed out
2025-05-30 08:09:47.387 ERROR (MainThread) [homeassistant.components.script.next_station] Next Station: Choose at step 1: choice 3: Error executing script. Error for call_service at pos 2: AVR command network_next returned error: AVR command 13NW timed out
2025-05-30 08:09:47.388 ERROR (MainThread) [homeassistant.components.script.next_station] Next Station: Error executing script. Error for choose at pos 1: AVR command network_next returned error: AVR command 13NW timed out
2025-05-30 08:09:47.391 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139715410145296] AVR command network_next returned error: AVR command 13NW timed out`

**Comment by crowbarz** [comment]
```
Entity media_player.pioneer_avr does not support action media_player.volume_set
```
This error is due to the integration only reporting to HA that volume can be set or muted after it has successfully queried the volume from the AVR. By default, the integration only queries the volume for the first time that the zone is powered on, either after HA starts, or after the integration reconnects when the AVR unit has been power cycled. Before the volume is queried, this error will be raised when trying to set the volume.

Here is the info level logging from my AVR, after HA was started with the AVR main zone powered off. The main zone was then powered on:
```
2025-06-01 23:06:19.535 INFO (MainThread) [aiopioneer.decode] Main Zone: power: False -> True ('0')
2025-06-01 23:06:19.584 INFO (MainThread) [aiopioneer.decode] Global: amp.display: None -> 'Cable' ('02202020204361626C652020202020')
2025-06-01 23:06:19.586 INFO (MainThread) [aiopioneer.decode] Main Zone: source_name: None -> 'Cable' ('06')
2025-06-01 23:06:19.586 INFO (MainThread) [aiopioneer.decode] Main Zone: source_id: None -> 6 ('06')
2025-06-01 23:06:22.041 INFO (MainThread) [aiopioneer.pioneer_avr] attempting initial refresh for Main Zone
2025-06-01 23:06:22.055 INFO (MainThread) [aiopioneer.decode] Global: listening_mode: None -> 'EXTENDED STEREO' ('0041')
2025-06-01 23:06:22.055 INFO (MainThread) [aiopioneer.decode] Global: listening_mode_id: None -> 41 ('0041')
2025-06-01 23:06:22.173 INFO (MainThread) [aiopioneer.decode] Main Zone: volume: None -> 91 ('091')
```
As you can see from the timestamps, there is a 2.638s delay between when the zone was reported as powered on and the volume was reported. Your script only waits 2.5s after turning on the AVR zone, so try increasing the delay to 3s or 3.5s. You may have to review the debug logs for your AVR and increase it by more as the timing may differ by AVR model.

You can also potentially resolve this issue by disabling the `Don't check volume when querying AVR source` advanced option in the HA integration. This will cause the volume for all zones to be queried immediately at integration startup and reconnect, and not delayed until the zone is powered on. The option defaults to enabled because not all AVRs support querying zone volume when the zone is powered off. IIRC there are also corner cases where it is unreliable, such as when HDZONE is powered on but the main zone is powered off.

**Comment by crowbarz** [comment]
> * it gives me an error up front - no actions are made, then second attempt will work.
> * it gives me an error as on video, the action is executed, but then I get error.

I can't exactly replicate your issue with `network_next` as I don't have a working network source - neither Spotify nor Internet Radio seem to work any more on my AVR.

However, I was able to reliably repro similar symptoms (action executes but is flagged as failed) by switching the source to `Internet Radio`, waiting 5 minutes, then changing the source to DVR. This causes the `select_source` command to fail the first time. The first retry works, but the response that the command executed isn't detected. The integration continues to retry, and eventually raises an error.

The retry behaviour should be fixed with 0.12.1 that was just released, and the sequence described above no longer repros on this version. It won't retry if the command times out, though, only when the AVR responds with an error.

**Comment by rakalex** [comment]
Upgraded to latest version. So far Volume issue seems gone, but still looking for errors. But "AVR command network_next returned error: AVR command 13NW timed out" still present, same as before. It changed to next track, but then thrown an error. So I think it's a common error, and it's not related to "next track" action at all.

**Comment by crowbarz** [comment]
It is more that the AVR API is not responding with a response starting with`NW` as documented. It does seem to respond with `NXA` in your debug logs, but I can't find any details about what this code means in the AVR API documentation.

If you think that the AVR is always executing the command, then you can add `wait_for_response: false` to the action data to prevent `send_command` from waiting for a response. This is the other new feature of 0.12.1.

**Comment by rakalex** [comment]
Still broken... I'm done. Man thanks for your work, but it's not working for me started from version 0.12 all automations are broken. Is it possible re-release 0.11 version with updates for HACS, because I cannot install it, seems it need some updates 

<img width="728" alt="Image" src="https://github.com/user-attachments/assets/06732dc4-1322-4bb8-a140-07c1a5029de5" />

**Comment by crowbarz** [comment]
I told you already in https://github.com/crowbarz/ha-pioneer_async/issues/79#issuecomment-2928032471 that you either need to increase the delay between turning on the AVR and setting the volume to 3 or more seconds in your script, or disable `Don't check volume when querying AVR source`, to fix the `volume_set` error. Have you done that? It is not sufficient just to upgrade the integration to the new version.

I can repro the HACS install issue, but I have no clue why it does not work. Also, I don't have the bandwidth to support releases other than the latest. You can restore an HA backup that has 0.11.0 installed if you have one. Or you could also try forking the repo, deleting the newer releases, removing the currently installed version, and installing via HACS from that fork instead.
